### ISSUE TITLE
tokenStart set to "{{" and tokenEnd set to "}}"

### ISSUE THREAD

**Issue by SecretBase** [rael9/token-replacement-ckeditor-plugin#2]
Hello Sir,

First, Nice plugin.

When I try setting tokenStart and tokenEnd to "{{"  and "}}" respectively.

It prompt an error:
![error](https://cloud.githubusercontent.com/assets/5130999/10071944/4469e366-62f0-11e5-943f-f9044f81a410.png)

**Comment by rael9** [comment]
Can you post the code where you defined the tokenStart and tokenEnd?

**Comment by SecretBase** [comment]
Sorry for confusion...

When I click the token dialog button, it prompt that error

Here is the code:

``` HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Testing</title>
    <style>
        main {
            max-width: 80%;
            margin: 0 auto;
        }
    </style>
    <script src="//cdn.ckeditor.com/4.5.3/standard/ckeditor.js"></script>
</head>
<body>
    <main>

        <textarea class="token-editor" id="editor" cols="30" rows="10"></textarea>

        <script>

            // var abc new CKEDITOR.resourceManager('http://localhost/testing/');
            CKEDITOR.plugins.addExternal('lineutils', '/testing/plugins/lineutils/', 'plugin.js');
            CKEDITOR.plugins.addExternal('widget', '/testing/plugins/widget/', 'plugin.js');
            CKEDITOR.plugins.addExternal('token', '/testing/plugins/token/', 'plugin.js');

            CKEDITOR.replaceAll(function (textarea, config) {

                config.extraPlugins = 'lineutils,widget,token';

                // Configure available tokens
                config.availableTokens = [
                    ["", ""],
                    ["token1", "token1"],
                    ["token2", "token2"],
                    ["token3", "token3"],
                ];

                config.tokenStart = '{{';
                config.tokenEnd = '}}';

                return true;
            });

        </script>

    </main>
</body>
</html>
```

---

### Here is some picture for your reference:

![code](https://cloud.githubusercontent.com/assets/5130999/10077757/3a76a046-6314-11e5-8b3b-7570b89b0dbd.png)

![code](https://cloud.githubusercontent.com/assets/5130999/10077997/67f94e8c-6315-11e5-92d8-9bc75218469f.png)

**Comment by rael9** [comment]
Interesting. It works for these combos:
'{', '}}'
'{', '}'
'${', '}'
'[[', ']]'

But not anything that starts with '{{'. My guess is that somewhere it isn't being properly handled as a string or something, but I haven't tracked it down yet. I'll take a look this evening and see if I can find anything.

**Comment by rael9** [comment]
It should be fixed now. Check out the latest version and let me know if it works out for you.

**Comment by SecretBase** [comment]
Work like charm !

Great Work Sir !
