### ISSUE TITLE
how to add to toolbars?

### ISSUE THREAD

**Issue by tablatronix** [rael9/token-replacement-ckeditor-plugin#3]
I can't seem to add to toolbar

`'Token'` not working

**Comment by rael9** [comment]
Did you follow the directions in the ReadMe.md? That _should_ get you up and running, unless something broke in some new version of CKEditor or something.

**Comment by tablatronix** [comment]
Yeah it works in full menu , but i cant seem to get the button on a custom toolbar.

**Comment by tablatronix** [comment]
Just looked at your source, looks like its `CreateToken` , a little confusing.

**Comment by rael9** [comment]
Sorry, misunderstood your original question. I can't recall why I used CreateToken, offhand. This plugin is largely based on the 'placeholder' plugin, so that could be part of the reason.
