### ISSUE TITLE
Incompatible token sentinals

### ISSUE THREAD

**Issue by tablatronix** [rael9/token-replacement-ckeditor-plugin#4]
It seems to choke on any token with a character following a `{` in either start or end token strings

```
    config.tokenStart = "{%";
    config.tokenEnd = "%}";
```

```
    config.tokenStart = "{A";
    config.tokenEnd = "A}";
```

```
Uncaught TypeError: 
Cannot read property 'AA' of undefined(anonymous function) @ VM7641:3
editor.addCommand.exec @ plugin.js?t=FB9E:1860
exec @ ckeditor.js:185
CKEDITOR.tools.extend.execCommand @ ckeditor.js:252
CKEDITOR.tools.extend.click @ ckeditor.js:669
d.execute @ ckeditor.js:670
(anonymous function) @ ckeditor.js:671(anonymous function) @ ckeditor.js:31
CKEDITOR.tools.callFunction @ ckeditor.js:31
onclick @ url..:1
```

**Comment by tablatronix** [comment]
Seems to be related to widget template. I have not had time to debug further, but if i remove the token from the string it works, so maybe this needs to be encoded or something.

```
template: '<span class="cke_token">' + tokenStart + tokenEnd + '</span>',
```

This is minimized source, Didnt have sourcemaps setup here.

```
        CKEDITOR.template = function(g) {
            if (a[g]) this.output = a[g];
            else {
                var h = g.replace(b, "\\$1").replace(c, "\\n").replace(e, "\\r").replace(d, function(a, b) {
                    return "',data['" + b + "']\x3d\x3dundefined?'{" + b + "}':data['" + b + "'],'"
                });
                this.output = a[g] = Function("data", "buffer", "return buffer?buffer.push('" + h + "'):['" + h + "'].join('');")
            }
        }
```

**Comment by rael9** [comment]
Ah, yes, this is fixed in the version here on GitHub. I will repackage it for ckeditor.com.

**Comment by tablatronix** [comment]
oh doh, my bad, I didn't realize master was newer than the plugin, i didn't even check the commits.

bef559436e4b8abb9de0d3deb42483d7bb1ff1d1

**Comment by tablatronix** [comment]
oh doh, my bad, I didn't realize master was newer than the plugin, i didn't even check the commits.

bef559436e4b8abb9de0d3deb42483d7bb1ff1d1

**Comment by rael9** [comment]
No worries. I should have remembered to update it on ckeditor.com. It's up to date on there, now, as well.
